# Generated by Django 3.2.15 on 2022-08-13 19:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eventsblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='scheduled_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 27, 19, 12, 3, 465956, tzinfo=utc)),
        ),
    ]
