# Generated by Django 3.2.15 on 2022-08-22 21:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eventsblog', '0003_alter_event_scheduled_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='eventsblog.event'),
        ),
        migrations.AlterField(
            model_name='event',
            name='scheduled_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 5, 21, 32, 19, 126746, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Scheduled'), (2, 'Cancelled')], default=0),
        ),
    ]
