# Generated by Django 3.2.15 on 2022-08-22 22:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eventsblog', '0004_auto_20220822_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='txt_preview',
            new_name='text_preview',
        ),
        migrations.AlterField(
            model_name='event',
            name='scheduled_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 5, 22, 1, 45, 812197, tzinfo=utc)),
        ),
    ]
