# Generated by Django 3.2.15 on 2022-08-27 11:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eventsblog', '0006_alter_event_scheduled_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='scheduled_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 10, 11, 2, 52, 578643, tzinfo=utc)),
        ),
    ]
